/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_TipTop;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import sistema_TipTop.datos.baseDatos;
import sistema_TipTop.pojos.personal;

/**
 *
 * @author Jose
 */
public class agregarNuevoPersonal extends javax.swing.JDialog {
//    FileInputStream fis;
//    int longitudBytes;
//    Image foto;
    
    baseDatos bd;
    File fotoPer;
    ImageIcon icon;
    
    boolean estaActualizando;
    String informacion = "";
    
   
    
    public agregarNuevoPersonal(java.awt.Frame parent, boolean modal, personal per, ImageIcon icon, String info, boolean actualizando) {

        bd = new baseDatos();


        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(650,490);
        this.setTitle("Actualizar Personal");
        

        this.informacion = info;
        this.estaActualizando = actualizando;
        this.icon = icon;

        if (per != null) {
            cargarPersonal(per, icon);
        }
    }
    
    public agregarNuevoPersonal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        bd = new baseDatos();
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(650,490);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txfCodigo = new javax.swing.JTextField();
        txfContrasenia = new javax.swing.JTextField();
        txfConfirContrasenia = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        btnExaminar = new javax.swing.JButton();
        txfNombre = new javax.swing.JTextField();
        txfDireccion = new javax.swing.JTextField();
        txfDomicilio = new javax.swing.JTextField();
        txfLugarNac = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txfSexo = new javax.swing.JTextField();
        txfFechaNac = new javax.swing.JTextField();
        txfEdad = new javax.swing.JTextField();
        txfFechaCont = new javax.swing.JTextField();
        txfTiempoLab = new javax.swing.JTextField();
        txfDni = new javax.swing.JTextField();
        txfRuc = new javax.swing.JTextField();
        txfCelular = new javax.swing.JTextField();
        txfTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnAgregarRol = new javax.swing.JButton();
        btnAgregarContacto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txfUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jLabel3.setText("Confirmacion de contraseña");

        jLabel4.setText("Nombre del personal");

        jLabel5.setText("Direccion del personal");

        jLabel6.setText("Domicilio fizcal");

        jLabel7.setText("Lugar de nacimiento");

        lblFoto.setBackground(new java.awt.Color(102, 102, 102));
        lblFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblFoto.setOpaque(true);

        btnExaminar.setText("Subir imagen");
        btnExaminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExaminarMouseClicked(evt);
            }
        });

        txfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDireccionActionPerformed(evt);
            }
        });

        txfDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDomicilioActionPerformed(evt);
            }
        });

        jLabel9.setText("Sexo");

        jLabel10.setText("Fecha de nacimiento");

        jLabel11.setText("Edad");

        jLabel12.setText("Fecha de inicio de contrato");

        jLabel13.setText("Tiempo laborado");

        jLabel14.setText("DNI");

        jLabel15.setText("RUC");

        jLabel16.setText("Celular");

        jLabel17.setText("Telefono fijo");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setText("Nuevo Personal");

        btnAgregarRol.setText("Agregar Rol");
        btnAgregarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRolActionPerformed(evt);
            }
        });

        btnAgregarContacto.setText("Agregar Contacto");
        btnAgregarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarContactoActionPerformed(evt);
            }
        });

        jLabel8.setText("Codigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(txfUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(117, 117, 117)
                        .addComponent(txfContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(22, 22, 22)
                        .addComponent(txfConfirContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(19, 19, 19)
                .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnExaminar))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(61, 61, 61)
                .addComponent(txfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addComponent(txfLugarNac, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addComponent(txfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(29, 29, 29)
                .addComponent(txfFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel9)
                .addGap(12, 12, 12)
                .addComponent(txfSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addGap(12, 12, 12)
                .addComponent(txfFechaCont, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel13)
                .addGap(16, 16, 16)
                .addComponent(txfTiempoLab, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel14)
                .addGap(12, 12, 12)
                .addComponent(txfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel15)
                .addGap(12, 12, 12)
                .addComponent(txfRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel16)
                .addGap(6, 6, 6)
                .addComponent(txfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel17)
                .addGap(6, 6, 6)
                .addComponent(txfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnAgregarContacto)
                .addGap(0, 0, 0)
                .addComponent(btnAgregarRol, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(btnGuardar)
                .addGap(4, 4, 4)
                .addComponent(btnCancelar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2))
                            .addComponent(txfContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3))
                            .addComponent(txfConfirContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4))
                            .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnExaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6))
                    .addComponent(txfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfLugarNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfFechaCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfTiempoLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarContacto)
                    .addComponent(btnAgregarRol)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDireccionActionPerformed

    private void txfDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDomicilioActionPerformed

    private void btnExaminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExaminarMouseClicked
//        lblFoto.setIcon(null);
//        JFileChooser fileChoose=new JFileChooser();
//        fileChoose.setFileSelectionMode(JFileChooser.FILES_ONLY);
//        int estado = fileChoose.showOpenDialog(null);
//        if(estado==JFileChooser.APPROVE_OPTION){
//            try{
//                fis= new FileInputStream(fileChoose.getSelectedFile());
//                this.longitudBytes=(int)fileChoose.getSelectedFile().length();
//                try{
//                     this.foto=ImageIO.read(fileChoose.getSelectedFile()).getScaledInstance
//                    (lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT);
//                    lblFoto.setIcon(new ImageIcon(foto));
//                    lblFoto.updateUI();
//                }catch(IOException ex){
//                JOptionPane.showMessageDialog(rootPane, "imagen: "+ex);
//                }
//            }catch(FileNotFoundException ex){
//            ex.printStackTrace();
//            }
//        }

        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Formatos permitidos jpg,jpge,gif o png", "jpg", "png", "gif");
        chooser.setFileFilter(filter);

        int returnval = chooser.showOpenDialog(this);
        if (returnval == JFileChooser.APPROVE_OPTION) {
            int anchoFoto = lblFoto.getWidth();
            int altoFoto = lblFoto.getHeight();
            fotoPer = chooser.getSelectedFile();
            ImageIcon icono = new ImageIcon(fotoPer.getAbsolutePath());
            Image imagen = icono.getImage();
            Image imagenRedimensionado = imagen.getScaledInstance(anchoFoto, altoFoto, Image.SCALE_DEFAULT);
            ImageIcon imagenRedimensionada = new ImageIcon(imagenRedimensionado);
            lblFoto.setIcon(imagenRedimensionada);

        }

    }//GEN-LAST:event_btnExaminarMouseClicked
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
//        PersonalFrame pf=new PersonalFrame();
//        pf.setLblFotoReciente(foto,fis);

        int idPersonal=Integer.parseInt(txfCodigo.getText());
          String nombre=txfNombre.getText();
          String usuario=txfUsuario.getText();
          String contrasenia=txfContrasenia.getText();
          String confiContra=txfConfirContrasenia.getText();
          String direccion=txfDireccion.getText();
          String domicilio=txfDomicilio.getText();
          String lugarNac=txfLugarNac.getText();
          String fechaNac=txfFechaNac.getText();
          String sexo=txfSexo.getText();
          int edad=Integer.parseInt(txfEdad.getText());
          String inicContra=txfFechaCont.getText();
          int tiempoLab=Integer.parseInt(txfTiempoLab.getText());
          int dni=Integer.parseInt(txfDni.getText());
          int ruc=Integer.parseInt(txfRuc.getText());
          int celular=Integer.parseInt(txfCelular.getText());
          int telefono=Integer.parseInt(txfTelefono.getText());
         
          ImageIcon foto=(ImageIcon) lblFoto.getIcon();
          
          if (estaActualizando) {
            if (fotoPer == null) {
                JOptionPane.showMessageDialog(this, "Inserte una imagen del personal", "Imagen del personal", JOptionPane.WARNING_MESSAGE);

            } else {
               personal persona = new personal(idPersonal, fotoPer, nombre, usuario, contrasenia,  direccion, domicilio, lugarNac, sexo, fechaNac, edad, inicContra, tiempoLab, dni, ruc,celular, telefono);
                bd.actualizarPersonal(persona);
                JOptionPane.showMessageDialog(this, "Se ha actualizado el articulo");
                this.dispose();
                this.informacion = "1";
            }

        } else {
            if (fotoPer == null) {
                JOptionPane.showMessageDialog(this, "Inserte una imagen del personal", "Imagen del personal", JOptionPane.WARNING_MESSAGE);
            } else {
                personal persona = new personal(idPersonal, fotoPer, nombre, usuario, contrasenia,  direccion, domicilio, lugarNac, sexo, fechaNac, edad, inicContra, tiempoLab, dni, ruc,celular, telefono);
                bd.insertarPersonal(persona);
                JOptionPane.showMessageDialog(null, "Los datos se han guardado correctamente");
                this.dispose();
            }
        }
          PersonalFrame pf=new PersonalFrame();
          pf.cargarModeloTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    public void cargarPersonal(personal per,ImageIcon icon){
       this.fotoPer = per.getFotoPer();

        lblFoto.setIcon(icon);
        int idPersonal=per.getIdPersonal();
        String nombre = per.getNombrePer();
        String usuario=per.getUsuarioPer();
        String contrasenia = per.getContraseniaPer();
        String direccion=per.getDireccionPer();
        String domicilio=per.getDomicilioFiscalPer();
        String lugarNac=per.getLugarNacPer();
        String fechaNac=per.getFechaNacPer();
        String sexo=per.getSexoPer();
        int edad=per.getEdadPer();
        String inicContra=per.getInicioContratoPer();
        int tiempoLab=per.getTiempoLaboradoPer();
        int dni=per.getDNIper();
        int ruc=per.getRUCper();
        int celular=per.getCelularPer();
        int telefono=per.getTelfPer();
        
        txfCodigo.setText(String.valueOf(idPersonal));
        txfNombre.setText(nombre);
        txfUsuario.setText(usuario);
        txfContrasenia.setText(contrasenia);
        txfDireccion.setText(direccion);
        txfDomicilio.setText(domicilio);
        txfLugarNac.setText(lugarNac);
        txfFechaNac.setText(fechaNac);
        txfSexo.setText(sexo);
        txfEdad.setText(String.valueOf(edad));
        txfFechaCont.setText(inicContra);
        txfTiempoLab.setText(String.valueOf(tiempoLab));
        txfDni.setText(String.valueOf(dni));
        txfRuc.setText(String.valueOf(ruc));
        txfCelular.setText(String.valueOf(celular));
        txfTelefono.setText(String.valueOf(telefono));

        txfCodigo.setEnabled(false);
        txfNombre.setEnabled(false);
        
    }
    
    private void btnAgregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarContactoActionPerformed
       areaContactosPersonal contactos=new areaContactosPersonal(null,true);
       contactos.setVisible(true);
       contactos.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
       contactos.setAlwaysOnTop(true);       
    }//GEN-LAST:event_btnAgregarContactoActionPerformed

    private void btnAgregarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRolActionPerformed
       areaRolesPersonal roles=new areaRolesPersonal(null,true);
       roles.setVisible(true);
       roles.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
       roles.setAlwaysOnTop(true);       
    }//GEN-LAST:event_btnAgregarRolActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public String getInformacion() {
        return this.informacion;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarNuevoPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarNuevoPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarNuevoPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarNuevoPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                agregarNuevoPersonal dialog = new agregarNuevoPersonal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarContacto;
    private javax.swing.JButton btnAgregarRol;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExaminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTextField txfCelular;
    private javax.swing.JTextField txfCodigo;
    private javax.swing.JTextField txfConfirContrasenia;
    private javax.swing.JTextField txfContrasenia;
    private javax.swing.JTextField txfDireccion;
    private javax.swing.JTextField txfDni;
    private javax.swing.JTextField txfDomicilio;
    private javax.swing.JTextField txfEdad;
    private javax.swing.JTextField txfFechaCont;
    private javax.swing.JTextField txfFechaNac;
    private javax.swing.JTextField txfLugarNac;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfRuc;
    private javax.swing.JTextField txfSexo;
    private javax.swing.JTextField txfTelefono;
    private javax.swing.JTextField txfTiempoLab;
    private javax.swing.JTextField txfUsuario;
    // End of variables declaration//GEN-END:variables
}
