package sistema_TipTop;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import sistema_TipTop.datos.baseDatos;
import sistema_TipTop.pojos.articulo;
import sistema_TipTop.pojos.categorias;
import sistema_TipTop.pojos.proveedor;

/**
 *
 * @author Jose
 */
public class areaArticulos extends javax.swing.JDialog {

    baseDatos bd;
    File fotoArt;
    ImageIcon icon;

    DefaultComboBoxModel<categorias> modeloCategorias;
    DefaultComboBoxModel<proveedor> modeloProveedor;

    boolean estaActualizando;
    String informacion = "";

    public areaArticulos(java.awt.Frame parent, boolean modal, articulo art, ImageIcon icon, String info, boolean actualizando) {

        bd = new baseDatos();
        modeloCategorias = new DefaultComboBoxModel<categorias>();
        modeloProveedor = new DefaultComboBoxModel<proveedor>();
        cargarModeloCategorias();
        cargarModeloProveedor();

        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(750, 300);
        this.setTitle("Actualizar Articulo");

        this.informacion = info;
        this.estaActualizando = actualizando;
        this.icon = icon;

        if (art != null) {
            cargarArticulo(art, icon);
        }
    }

    public areaArticulos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        bd = new baseDatos();
        modeloCategorias = new DefaultComboBoxModel<categorias>();
        modeloProveedor = new DefaultComboBoxModel<proveedor>();
        cargarModeloCategorias();
        cargarModeloProveedor();

        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(750, 300);
        this.setTitle("Area de Articulos");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txfDescripcion = new javax.swing.JTextField();
        txfPrecVenta = new javax.swing.JTextField();
        txfClave = new javax.swing.JTextField();
        txfNombre = new javax.swing.JTextField();
        txfExistencias = new javax.swing.JTextField();
        txfPrecCompra = new javax.swing.JTextField();
        txfStock = new javax.swing.JTextField();
        txfUnidMedida = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExaminar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        cbxProveedor = new javax.swing.JComboBox<>();
        cbxCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFoto.setBackground(new java.awt.Color(102, 102, 102));
        lblFoto.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 180));

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel3.setText("Clave");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jLabel4.setText("Descripción");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jLabel5.setText("Stock");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jLabel6.setText("Unidad de Medida");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        jLabel7.setText("Precio de venta");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel8.setText("Precio de compra");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel10.setText("Categoria ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        jLabel11.setText("Proveedor");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));
        getContentPane().add(txfDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 260, 40));

        txfPrecVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPrecVentaActionPerformed(evt);
            }
        });
        getContentPane().add(txfPrecVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 140, -1));
        getContentPane().add(txfClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 201, -1));
        getContentPane().add(txfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 201, -1));
        getContentPane().add(txfExistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 70, -1));
        getContentPane().add(txfPrecCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 140, -1));
        getContentPane().add(txfStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 90, -1));
        getContentPane().add(txfUnidMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 70, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 90, 70));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 90, 70));

        btnExaminar.setText("Examinar");
        btnExaminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExaminarMouseClicked(evt);
            }
        });
        getContentPane().add(btnExaminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 20));

        jLabel12.setText("Existencias");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        cbxProveedor.setModel(modeloProveedor);
        getContentPane().add(cbxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 110, -1));

        cbxCategoria.setModel(modeloCategorias);
        getContentPane().add(cbxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfPrecVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPrecVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPrecVentaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        String nombre = txfNombre.getText();
        int clave = Integer.parseInt(txfClave.getText());
        String descripcion = txfDescripcion.getText();
        int stock = Integer.parseInt(txfStock.getText());
        double uMedida = Double.parseDouble(txfUnidMedida.getText());
        double pCompra = Double.parseDouble(txfPrecCompra.getText());
        double pVenta = Double.parseDouble(txfPrecVenta.getText());
        categorias cat = (categorias) cbxCategoria.getSelectedItem();
        proveedor prov = (proveedor) cbxProveedor.getSelectedItem();
        int existencias = Integer.parseInt(txfExistencias.getText());
        
        ImageIcon foto=(ImageIcon) lblFoto.getIcon();
        
        if (estaActualizando) {
            if (fotoArt == null) {
                JOptionPane.showMessageDialog(this, "Inserte una imagen del producto11", "Imagen del producto", JOptionPane.WARNING_MESSAGE);

            } else {
                articulo art = new articulo(clave, nombre, descripcion, stock, uMedida, pVenta, pCompra, cat.getIdCategoria(), prov.getIdProveedor(), existencias, fotoArt);
                bd.actualizarArticulo(art);
                JOptionPane.showMessageDialog(this, "Se ha actualizado el articulo");
                this.dispose();
                this.informacion = "1";
            }

        } else {
            if (fotoArt == null) {
                JOptionPane.showMessageDialog(this, "Inserte una imagen del producto", "Imagen del producto", JOptionPane.WARNING_MESSAGE);
            } else {
                articulo art = new articulo(clave, nombre, descripcion, stock, uMedida, pVenta, pCompra, cat.getIdCategoria(), prov.getIdProveedor(), existencias, fotoArt);
                bd.insertarArticulo(art);
                JOptionPane.showMessageDialog(null, "Los datos se han guardado correctamente");
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    public String getInformacion() {
        return this.informacion;
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExaminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExaminarMouseClicked
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Formatos permitidos jpg,jpge,gif o png", "jpg", "png", "gif");
        chooser.setFileFilter(filter);

        int returnval = chooser.showOpenDialog(this);
        if (returnval == JFileChooser.APPROVE_OPTION) {
            int anchoFoto = lblFoto.getWidth();
            int altoFoto = lblFoto.getHeight();
            fotoArt = chooser.getSelectedFile();
            ImageIcon icono = new ImageIcon(fotoArt.getAbsolutePath());
            Image imagen = icono.getImage();
            Image imagenRedimensionado = imagen.getScaledInstance(anchoFoto, altoFoto, Image.SCALE_DEFAULT);
            ImageIcon imagenRedimensionada = new ImageIcon(imagenRedimensionado);
            lblFoto.setIcon(imagenRedimensionada);

        }
    }//GEN-LAST:event_btnExaminarMouseClicked

    private void cargarModeloCategorias() {
        ArrayList<categorias> listaCategorias;
        listaCategorias = bd.obtenerCategorias();

        for (categorias categoria : listaCategorias) {
            modeloCategorias.addElement(categoria);
        }
    }

    private void cargarModeloProveedor() {
        ArrayList<proveedor> listaProveedor;
        listaProveedor = bd.obtenerProveedores();

        for (proveedor prov : listaProveedor) {
            modeloProveedor.addElement(prov);
        }
    }

    public void cargarArticulo(articulo art, ImageIcon icon) {

        this.fotoArt = art.getFotoArticulo();

        lblFoto.setIcon(icon);
        String nombre = art.getNombreArt();
        int clave = art.getIdArticulo();
        String descripcion = art.getDescArticulo();
        int stock = art.getStockArticulo();
        double uMedida = art.getuMedidaArticulo();
        double pCompra = art.getpCompraArticulo();
        double pVenta = art.getpVentaArticulo();
        int existencias = art.getExistenciasArticulo();

        txfNombre.setText(nombre);
        txfClave.setText(String.valueOf(clave));
        txfDescripcion.setText(descripcion);
        txfStock.setText(String.valueOf(stock));
        txfUnidMedida.setText(String.valueOf(uMedida));
        txfPrecCompra.setText(String.valueOf(pCompra));
        txfPrecVenta.setText(String.valueOf(pVenta));
        txfExistencias.setText(String.valueOf(existencias));

        txfClave.setEnabled(false);
        txfNombre.setEnabled(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(areaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(areaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(areaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(areaArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                areaArticulos dialog = new areaArticulos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExaminar;
    private javax.swing.JComboBox<categorias> cbxCategoria;
    private javax.swing.JComboBox<proveedor> cbxProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTextField txfClave;
    private javax.swing.JTextField txfDescripcion;
    private javax.swing.JTextField txfExistencias;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfPrecCompra;
    private javax.swing.JTextField txfPrecVenta;
    private javax.swing.JTextField txfStock;
    private javax.swing.JTextField txfUnidMedida;
    // End of variables declaration//GEN-END:variables
}
